import Head from 'next/head'
import Navbar from '../Navbar'
import style from './MainLayout.module.css'
import { FC } from 'react'

interface Props {
  children : JSX.Element | JSX.Element[],
  styles: Object
}

const MainLayout :FC<Props> = ({children, styles}) => {
  return (
    <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={style.main} style={styles}>
        {children}
      </main>
    </>
  )
}

export default MainLayout